URFaveBooks/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.logreg_app.urls', namespace="Users")),
    url(r'^books/', include('apps.books_app.urls', namespace="Books")),
]

apps/books_app/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^success$', views.success, name = "Success"), #HomePage
    url(r'^create$', views.create, name = "Create"), #Creating the book 
    url(r'^(?P<number>\d+)$', views.displaybook, name='Displaybook'), # Display the book
    url(r'^logout$', views.logout, name = "logout"),
    # url(r'^user/(?P<user_id>\d+)$', views.show)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/books_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import datetime
import re
from django.core.exceptions import ObjectDoesNotExist
from ..logreg_app.models import Users
from django.core.files import File

# Create your models here.
class BooksValidator (models.Manager):
    def validateBooks(self, postDate, postFILES, current_user):
        errors = {}
        new_author = False
        if postDate['rating'] == 'selected':
            errors["rating"] = "Please choose a rating"
        # if (int(postDate['rating']) < 1 ) | (int(postDate['rating']) > 5):
        #     errors["rating"] = "Rating should be between 0 and 5"
        if len(postDate['title']) < 3:
            errors['title'] = "Title must have more then 2 characters" 
        if len(postDate['review']) < 10:
            errors['review'] = 'Your review needs to be more than 10 characters long before submitting'
        if postDate['selected_author'] == 'selected_author' and postDate['inputed_author'] == 'author_name':
            errors['selected_author'] = 'An author must be selected or added before submiting form'
        # if postDate['selected_author'] != 'selected_author' and postDate['inputed_author'] != 'author_name':
        #     errors['selected_author'] = 'You cannot try to add an author and create one at the same time'
        try:
            #is the author already in the database?
            Authors.objects.get(author_name = postDate['inputed_author'])
            errors['inputed_author'] = 'This author is already been created'
        except Exception:
            if postDate['inputed_author'] != 'author_name':    
                new_author = True
        try:
            Books.objects.get(title=postDate['title'])
            errors['title'] = "Book is already created"
        except Exception:
           if postDate['title'] != 'title':
                print errors
        if errors:
            return (errors)

        # What author selection was used?
        #IF (TRUE) there was a NEW author selected 
        if new_author:
            #what is the name of the new author?
            input_created_author = postDate['inputed_author']
            print input_created_author 
            print  "Created Author^^^^^^"
            #create the author and store in VAR
            new_author = Authors.objects.create(author_name = input_created_author)
            #Put the new author in a new VAR to use when CREATING the BOOK
            author_for_book_created = new_author
        else:
            #IF FALSE 
            #take the name of the SELECTED author
            selected_author = postDate['selected_author']
            print selected_author
            print  "Selected Author^^^^^^"
            #find the name of the selected author
            author_for_book_created = Authors.objects.get(author_name = selected_author)
        
          #Try grabbing an image if it was uploaded
        try:
            book_covers = postFILES['book_covers']
            print book_covers
        except:
            book_covers = ''
            print 'No image'

        #Creating a new book
        title = postDate['title']
        user_id = postDate['user_id']
        book_covers = book_covers
        new_book_created = Books.objects.create(title=title, author=author_for_book_created, user_id=user_id , book_covers=book_covers)
        print new_book_created

        #Create the review
        print "IN --> create REVIEW"
        text = postDate['review']
        rating = postDate['rating']
        reviewer = postDate['user_id']
        book_review = Reviews.objects.create(text=text, rating=rating, reviewer_id=reviewer, book=new_book_created)
        # print book_review
        if errors:
            return errors

class Authors(models.Model):
    author_name = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = BooksValidator()

class Books(models.Model):
    title = models.CharField(max_length = 255)
    author = models.ForeignKey(Authors, related_name='authors')
    user = models.ForeignKey(Users, related_name = "who_created_book", null=True)
    book_covers = models.ImageField(upload_to="'uploads/%Y/%m'", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = BooksValidator()

    def __str__(self):
        return "Title: " + self.title

    def __repr__(self):
        return "<Books object: title: {}, author: {} >".format(self.title, self.author)

class Reviews(models.Model):
    text = models.TextField(default = "N/A")
    rating = models.IntegerField()
    book = models.ForeignKey(Books, related_name = "book_reviewed")
    reviewer = models.ForeignKey(Users, related_name = "who_reviewed_book")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return "Reviews: " + self.reviewer

    def __repr__(self):
        return "<Reviews Object: text: {}, rating: {}, book: {}, reviewer: {}>".format(self.text, self.rating, self.reviewer, self.book)




            

apps/books_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from models import *
from models import Books, Authors, Reviews
from ..logreg_app.models import *
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.shortcuts import render, redirect, reverse


# Create your views here.
def success(request):
    # if request.session['user_id'] == None:
    #     return redirect(reverse('Users:index'))
    print "Books/Success Page "
    context = {
        'user': Users.objects.all(),
        'current_user': Users.objects.get(id=request.session['user_id']),
        'books': Books.objects.all(),
        'reviews' : Reviews.objects.last(),
        }
    return render(request, "success.html", context)

def create(request):
    current_user = request.session['user_id']
    find_authors = Authors.objects.all()
    # if request.session['user_id'] == None:
    #     return redirec==t(reverse('Users:index'))
    if request.method == "POST":
        errors = Books.objects.validateBooks(request.POST, request.FILES , current_user)
        if errors:
            for tag, error in errors.iteritems():
                messages.error(request, error, extra_tags=tag)
            return redirect(reverse('Books:Create'))
    else:
        context = {
            'authors' : find_authors
        }
    return render(request, 'create.html', {'authors': find_authors})

def displaybook(request):
    return render(request, 'displaybook.html')

def logout(request):
    request.session.clear()
    return redirect('/')

apps/books_app/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
     
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy"
        crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">
    <script>

    </script>
    <style>
        .navbar {
            background-color: #3f2f23;
            padding: 20px;
            width: 1700px;
            color: #f1e7d6;
        }
    
        .navbar-LOGO {
            font-style: italic;
            font-family: Verdana, Geneva, Tahoma, sans-serif;
            font-weight: 500;
            color: #f1e7d6;
            margin-right: 880px;
        }
    
        a {
            color: #f1e7d6;
        }
        .container-fluid form{
            padding: 150px;
        }
        .input-group{
            margin-bottom: 30px;
        }
        select{
            margin-bottom: 30px;
        }
    </style>
    <title>Book Review Login and Register</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <h1 class="navbar-LOGO">UR - Fave - Books</h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
    
            <ul class="navbar-nav">
                <!-- HOME BUTTON -->
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Books:Success' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
    
                <!-- CREATE A BOOK BUTTON -->
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Books:Create' %}"> Create a Book
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
    
                <!-- DROPDOWN / PROFILE / RECENT BOOKS / YOUR BOOKS/  -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown link
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Profile</a>
                        <a class="dropdown-item" href="#">Recent Reviews</a>
                        <a class="dropdown-item" href="#">Your Books</a>
                    </div>
                </li>
    
                <!-- LOGOUT BUTTON -->
                <li class="nav-item active">
                    <form action="logout" method="post">
                        {% csrf_token %}
                        <input type="submit" name="logout" value="logout">
                    </form>
                </li>
    
            </ul>
        </div>
    </nav>

    <div class="container-fluid">
        <form action="/books/create" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- TITLE -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Title</span>
                </div>
                <input type="text" name="title" class="form-control">
            </div>

            <!-- AUTHOR -->
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="inputGroupSelect01">Choose an Author</label>
                </div>
                <select name="selected_author" class="custom-select" id="inputGroupSelect01">
                    <option selected name="selected_author" value="None">Choose...</option>
                    {% for author in authors %}
                    <option value="{{ author.author_name }}">{{ author.author_name}}</option>
                    {% endfor %}
                </select>
            </div>
            <!-- <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Book Author</span>
                </div>
                <select name="selected_author">
                    <option name="selected_author" value="None"></option>
                    {% for author in authors %}
                    <option value="{{ author.author_name }}">{{ author.author_name}}</option>
                    {% endfor %}
                </select>
            </div> -->

                <!-- New AUTHOR -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Create a Book Author</span>
                </div>
                <input type="text" name="inputed_author" value="author_name" class="form-control">
            </div>

                <!-- REVIEW -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Review</span>
                </div>
                <input type="text" name="review" class="form-control">
            </div>
            
            <!-- RATING -->
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="inputGroupSelect01">Star Rating</label>
                </div>
                <select name="rating" class="custom-select"  id="inputGroupSelect01">
                    <option selected>Choose...</option>
                    <option value="0">1</option>
                    <option value="1">2</option>
                    <option value="2">3</option>
                    <option value="3">4</option>
                    <option value="3">5</option>
                </select>
            </div>

            <!-- Book Covers /IMG Upload -->
            <h4>Would you like to upload a book cover?</h4>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Upload</span>
                    </div>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile01" name="book_covers" accept="image/*">
                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                    </div>
                </div> 


            <input type="hidden" name="user_id" value="{{ request.session.user_id }}">
            <input type="submit" name="submit" value="Add New Book"  class="btn btn-lg btn-outline">
            
            <!-- <input type="hidden" name="current_user_name" value="{{ request.session.current_user.name }}"> -->
        </form>
    </div>
     {% if messages %} {% for message in messages %}
    <p {% if messages.tags %} {% endif %}>
        {{ message }}</p>
    {% endfor %} {% endif %}
</body>
</html>

apps/books_app/templates/displaybook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy"
        crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">
    <title>Welcome to URFaveBooks!</title>
    <style>
       
    </style>
</head>
<body>
   
</body>
</html>

apps/books_app/templates/new_book.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy"
        crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/newbook.css' %}">
    <link rel="stylesheet" type="text/js" href="{% static 'js/newbook.js' %}">
    <script>

    </script>
    <title>Book Review Login and Register</title>
</head>
<body>
    <!-- NAVIGATION BAR -->
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/">UR - Fave - Books</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown link
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        <form action="/new_book" method="POST">
            {% csrf_token %}
            <!-- TITLE -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Title</span>
                </div>
                <input type="text" name="title" class="form-control">
            </div>
            <!-- AUTHOR -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Book Author</span>
                </div>
                <select name="author" id="">
                    <option value="None">N/A</option>
                    {% for author in authors %}
                    <option value="{{ author.author }}">{{ author.author}}</option>
                    {% endfor %}
                </select>
            </div>
                <!-- New AUTHOR -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Book Author</span>
                </div>
                <input type="text" name="inputed_author" class="form-control">
            </div>

                <!-- REVIEW -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Review</span>
                </div>
                <input type="text" name="review" class="form-control">
            </div>
            
            <!-- RATING -->
            <select name="rating" id="">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
            <input type="hidden" name="current_user_id" value="{{ request.session.current_user.id }}">
            <input type="submit" name="submit" value="Add New Book"  class="btn btn-lg btn-outline">
            
            <!-- <input type="hidden" name="current_user_name" value="{{ request.session.current_user.name }}"> -->
        </form>
    </div>
</body>
</html>

apps/books_app/templates/newbook.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy"
        crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/newbook.css' %}">
    <link rel="stylesheet" type="text/js" href="{% static 'js/newbook.js' %}">
    <script>

    </script>
    <title>Book Review Login and Register</title>
</head>
<body>
    <!-- NAVIGATION BAR -->
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/">UR - Fave - Books</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown link
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        <form action="newBook" method="post">
            {% csrf_token %}
            <!-- TITLE -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Title</span>
                </div>
                <input type="text" name="title" class="form-control">
            </div>
                <!-- AUTHOR -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Author</span>
                </div>
                <input type="text" name="author" class="form-control">
            </div>

                <!-- NEW AUTHOR -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Book Author</span>
                </div>
                <input type="text" name="new_input_author" class="form-control">
            </div>

                <!-- REVIEW -->
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Review</span>
                </div>
                <input type="text" name="review" class="form-control">
            </div>
            
                <input type="button" type="submit" name="submit" value="Submit"  class="btn btn-lg btn-outline">
        </form>
    </div>
</body>
</html>

apps/books_app/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">
    <title>Welcome to URFaveBooks!</title>
    <style>
    .navbar{
        background-color: #3f2f23;
        padding: 20px;
        width: 1700px;
        color: #f1e7d6;
     }
    .navbar-LOGO{
        font-style: italic;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        font-weight: 500;
        color: #f1e7d6;
         margin-right: 880px;
    }
    a{
        color: #f1e7d6;
    }
    .card{
        display: inline-block;
        margin: 30px;
    }
    .card-title{
        margin-bottom: 0px;
    }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <h1 class="navbar-LOGO">UR - Fave - Books</h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
               
                <ul class="navbar-nav">
                <!-- HOME BUTTON -->
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'Books:Success' %}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>

                <!-- CREATE A BOOK BUTTON -->
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'Books:Create' %}"> Create a Book 
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>

                <!-- DROPDOWN / PROFILE / RECENT BOOKS / YOUR BOOKS/  -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown link
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Profile</a>
                            <a class="dropdown-item" href="#">Recent Reviews</a>
                            <a class="dropdown-item" href="#">Your Books</a>
                        </div>
                    </li>

                <!-- LOGOUT BUTTON -->
                    <li class="nav-item active">
                        <form action="logout" method="post">
                            {% csrf_token %}
                            <input type="submit" name="logout" value="logout">
                        </form>
                    </li>
               
                </ul>
            </div>
        </nav>

        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">Success! Welcome, {{ current_user.first_name }}</h1>
               
            </div>
        </div>

    <div class="container-fluid">
        <!-- BOOKS -->
        {% for book in books %}
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="media/{{book.book_covers}}" alt="{{ books.title }}">
            <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5> 
                <small class="text-muted">By: {{ book.author.author_name }}</small>
                <p class="card-text">{{ reviews.rating }} Make it average book rating</p>
            </div>
        
            <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ reviews.text }}</li>
            </ul>
            
            <div class="card-body">
                <!-- <a href="#" class="card-link"></a> -->
                <a href="display/{{book.id}}" class="card-link">See More Reviews!</a>
            </div>
        </div>
        {% endfor %}
    </div>
</body>

</html>